import type { PatientData } from "./types";

export const samplePatient: PatientData = {
  patientName: "Sarah Chen",
  readings: [
    {
      testName: "LDL Cholesterol",
      value: 110,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 100,
      date: "2020-03-12",
      source: "Quest Diagnostics",
    },
    {
      testName: "HDL Cholesterol",
      value: 52,
      unit: "mg/dL",
      referenceLow: 40,
      referenceHigh: null,
      date: "2020-03-12",
      source: "Quest Diagnostics",
    },
    {
      testName: "Total Cholesterol",
      value: 185,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 200,
      date: "2020-03-12",
      source: "Quest Diagnostics",
    },
    {
      testName: "Triglycerides",
      value: 130,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 150,
      date: "2020-03-12",
      source: "Quest Diagnostics",
    },
    {
      testName: "Hemoglobin A1C",
      value: 5.4,
      unit: "%",
      referenceLow: 4,
      referenceHigh: 5.6,
      date: "2020-03-12",
      source: "Quest Diagnostics",
    },
    {
      testName: "Vitamin D, 25-Hydroxy",
      value: 24,
      unit: "ng/mL",
      referenceLow: 30,
      referenceHigh: 100,
      date: "2020-03-12",
      source: "Quest Diagnostics",
    },
    {
      testName: "TSH",
      value: 1.9,
      unit: "mIU/L",
      referenceLow: 0.4,
      referenceHigh: 4,
      date: "2020-03-12",
      source: "Quest Diagnostics",
    },
    {
      testName: "LDL Cholesterol",
      value: 118,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 100,
      date: "2020-11-05",
      source: "LabCorp",
    },
    {
      testName: "HDL Cholesterol",
      value: 50,
      unit: "mg/dL",
      referenceLow: 40,
      referenceHigh: null,
      date: "2020-11-05",
      source: "LabCorp",
    },
    {
      testName: "Total Cholesterol",
      value: 194,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 200,
      date: "2020-11-05",
      source: "LabCorp",
    },
    {
      testName: "Triglycerides",
      value: 138,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 150,
      date: "2020-11-05",
      source: "LabCorp",
    },
    {
      testName: "Hemoglobin A1C",
      value: 5.5,
      unit: "%",
      referenceLow: 4,
      referenceHigh: 5.6,
      date: "2020-11-05",
      source: "LabCorp",
    },
    {
      testName: "Vitamin D, 25-Hydroxy",
      value: 22,
      unit: "ng/mL",
      referenceLow: 30,
      referenceHigh: 100,
      date: "2020-11-05",
      source: "LabCorp",
    },
    {
      testName: "TSH",
      value: 2.3,
      unit: "mIU/L",
      referenceLow: 0.4,
      referenceHigh: 4,
      date: "2020-11-05",
      source: "LabCorp",
    },
    {
      testName: "LDL Cholesterol",
      value: 126,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 100,
      date: "2021-06-18",
      source: "Mount Sinai Hospital",
    },
    {
      testName: "HDL Cholesterol",
      value: 49,
      unit: "mg/dL",
      referenceLow: 40,
      referenceHigh: null,
      date: "2021-06-18",
      source: "Mount Sinai Hospital",
    },
    {
      testName: "Total Cholesterol",
      value: 205,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 200,
      date: "2021-06-18",
      source: "Mount Sinai Hospital",
    },
    {
      testName: "Triglycerides",
      value: 145,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 150,
      date: "2021-06-18",
      source: "Mount Sinai Hospital",
    },
    {
      testName: "Hemoglobin A1C",
      value: 5.6,
      unit: "%",
      referenceLow: 4,
      referenceHigh: 5.6,
      date: "2021-06-18",
      source: "Mount Sinai Hospital",
    },
    {
      testName: "Vitamin D, 25-Hydroxy",
      value: 26,
      unit: "ng/mL",
      referenceLow: 30,
      referenceHigh: 100,
      date: "2021-06-18",
      source: "Mount Sinai Hospital",
    },
    {
      testName: "TSH",
      value: 2.1,
      unit: "mIU/L",
      referenceLow: 0.4,
      referenceHigh: 4,
      date: "2021-06-18",
      source: "Mount Sinai Hospital",
    },
    {
      testName: "LDL Cholesterol",
      value: 137,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 100,
      date: "2022-04-22",
      source: "Stamford Health",
    },
    {
      testName: "HDL Cholesterol",
      value: 51,
      unit: "mg/dL",
      referenceLow: 40,
      referenceHigh: null,
      date: "2022-04-22",
      source: "Stamford Health",
    },
    {
      testName: "Total Cholesterol",
      value: 214,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 200,
      date: "2022-04-22",
      source: "Stamford Health",
    },
    {
      testName: "Triglycerides",
      value: 152,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 150,
      date: "2022-04-22",
      source: "Stamford Health",
    },
    {
      testName: "Hemoglobin A1C",
      value: 5.7,
      unit: "%",
      referenceLow: 4,
      referenceHigh: 5.6,
      date: "2022-04-22",
      source: "Stamford Health",
    },
    {
      testName: "Vitamin D, 25-Hydroxy",
      value: 25,
      unit: "ng/mL",
      referenceLow: 30,
      referenceHigh: 100,
      date: "2022-04-22",
      source: "Stamford Health",
    },
    {
      testName: "TSH",
      value: 1.8,
      unit: "mIU/L",
      referenceLow: 0.4,
      referenceHigh: 4,
      date: "2022-04-22",
      source: "Stamford Health",
    },
    {
      testName: "LDL Cholesterol",
      value: 148,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 100,
      date: "2023-02-14",
      source: "Quest Diagnostics",
    },
    {
      testName: "HDL Cholesterol",
      value: 48,
      unit: "mg/dL",
      referenceLow: 40,
      referenceHigh: null,
      date: "2023-02-14",
      source: "Quest Diagnostics",
    },
    {
      testName: "Total Cholesterol",
      value: 225,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 200,
      date: "2023-02-14",
      source: "Quest Diagnostics",
    },
    {
      testName: "Triglycerides",
      value: 162,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 150,
      date: "2023-02-14",
      source: "Quest Diagnostics",
    },
    {
      testName: "Hemoglobin A1C",
      value: 5.8,
      unit: "%",
      referenceLow: 4,
      referenceHigh: 5.6,
      date: "2023-02-14",
      source: "Quest Diagnostics",
    },
    {
      testName: "Vitamin D, 25-Hydroxy",
      value: 28,
      unit: "ng/mL",
      referenceLow: 30,
      referenceHigh: 100,
      date: "2023-02-14",
      source: "Quest Diagnostics",
    },
    {
      testName: "TSH",
      value: 2.5,
      unit: "mIU/L",
      referenceLow: 0.4,
      referenceHigh: 4,
      date: "2023-02-14",
      source: "Quest Diagnostics",
    },
    {
      testName: "LDL Cholesterol",
      value: 158,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 100,
      date: "2024-01-30",
      source: "LabCorp",
    },
    {
      testName: "HDL Cholesterol",
      value: 49,
      unit: "mg/dL",
      referenceLow: 40,
      referenceHigh: null,
      date: "2024-01-30",
      source: "LabCorp",
    },
    {
      testName: "Total Cholesterol",
      value: 233,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 200,
      date: "2024-01-30",
      source: "LabCorp",
    },
    {
      testName: "Triglycerides",
      value: 172,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 150,
      date: "2024-01-30",
      source: "LabCorp",
    },
    {
      testName: "Hemoglobin A1C",
      value: 6,
      unit: "%",
      referenceLow: 4,
      referenceHigh: 5.6,
      date: "2024-01-30",
      source: "LabCorp",
    },
    {
      testName: "Vitamin D, 25-Hydroxy",
      value: 23,
      unit: "ng/mL",
      referenceLow: 30,
      referenceHigh: 100,
      date: "2024-01-30",
      source: "LabCorp",
    },
    {
      testName: "TSH",
      value: 2.2,
      unit: "mIU/L",
      referenceLow: 0.4,
      referenceHigh: 4,
      date: "2024-01-30",
      source: "LabCorp",
    },
    {
      testName: "LDL Cholesterol",
      value: 165,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 100,
      date: "2025-03-10",
      source: "Stamford Health",
    },
    {
      testName: "HDL Cholesterol",
      value: 48,
      unit: "mg/dL",
      referenceLow: 40,
      referenceHigh: null,
      date: "2025-03-10",
      source: "Stamford Health",
    },
    {
      testName: "Total Cholesterol",
      value: 240,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 200,
      date: "2025-03-10",
      source: "Stamford Health",
    },
    {
      testName: "Triglycerides",
      value: 180,
      unit: "mg/dL",
      referenceLow: null,
      referenceHigh: 150,
      date: "2025-03-10",
      source: "Stamford Health",
    },
    {
      testName: "Hemoglobin A1C",
      value: 6.1,
      unit: "%",
      referenceLow: 4,
      referenceHigh: 5.6,
      date: "2025-03-10",
      source: "Stamford Health",
    },
    {
      testName: "Vitamin D, 25-Hydroxy",
      value: 27,
      unit: "ng/mL",
      referenceLow: 30,
      referenceHigh: 100,
      date: "2025-03-10",
      source: "Stamford Health",
    },
    {
      testName: "TSH",
      value: 2,
      unit: "mIU/L",
      referenceLow: 0.4,
      referenceHigh: 4,
      date: "2025-03-10",
      source: "Stamford Health",
    },
  ],
};
